USE [ESTUDOS];
GO

CREATE TABLE [dbo].[TABELA DE VENDEDORES](
	[MATRICULA] [varchar](5) NULL,
	[NOME] [varchar](100) NULL,
	[PERCENTUAL COMISSÃO] [float] NULL
) ON [PRIMARY]
GO

DROP TABLE [dbo].[TABELA DE VENDEDORES];


