SELECT 
  C.BAIRRO, 
  'Cliente' AS 'Oriegm' 
FROM [TABELA DE CLIENTES] AS C UNION 
SELECT 
  DISTINCT V.BAIRRO, 
  'Vendedor' AS 'Oriegm' 
FROM [TABELA DE VENDEDORES] AS V

SELECT 
  C.BAIRRO, 
  'Cliente' AS 'Oriegm' 
FROM [TABELA DE CLIENTES] AS C  UNION ALL
SELECT 
  V.BAIRRO, 
  'Vendedor' AS 'Oriegm' 
FROM [TABELA DE VENDEDORES] AS V
ORDER BY C.BAIRRO

/* Não executa, os campos devem ser iguais */
SELECT 
  DISTINCT [TABELA DE CLIENTES].[BAIRRO], 
  [TABELA DE CLIENTES].[DATA DE NASCIMENTO] 
FROM [TABELA DE CLIENTES]
UNION ALL
SELECT 
  DISTINCT [TABELA DE VENDEDORES].BAIRRO, 
  [TABELA DE VENDEDORES].[NOME] 
FROM [TABELA DE VENDEDORES]

SELECT 
  C.[BAIRRO], 
  C.[NOME], 
  'Cliente' AS 'Origem'
FROM [TABELA DE CLIENTES] AS C
UNION ALL
SELECT 
  V.BAIRRO, 
  V.[NOME],
  'Vendedor' AS 'Origem'
FROM [TABELA DE VENDEDORES] AS V

