SELECT [EMBALAGEM] ,[TAMANHO]      
FROM [SUCOS_VENDAS].[dbo].[TABELA DE PRODUTOS]
ORDER BY EMBALAGEM;

SELECT DISTINCT [EMBALAGEM] ,[TAMANHO]      
FROM [SUCOS_VENDAS].[dbo].[TABELA DE PRODUTOS]
ORDER BY EMBALAGEM;

