SELECT * FROM [dbo].[TABELA DE CLIENTES]

SELECT ESTADO, SUM([LIMITE DE CREDITO]) AS soma 
FROM [TABELA DE CLIENTES] GROUP BY ESTADO

SELECT ESTADO, SUM([LIMITE DE CREDITO]) AS soma 
FROM [TABELA DE CLIENTES] 
GROUP BY ESTADO 
HAVING SUM([LIMITE DE CREDITO]) >= 850000

SELECT EMBALAGEM, SUM([PREÇO DE LISTA]) AS soma, MAX([PREÇO DE LISTA]) AS maximo, MIN([PREÇO DE LISTA]) AS minimo  
FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM 
HAVING SUM([PREÇO DE LISTA]) <= 80

SELECT EMBALAGEM, SUM([PREÇO DE LISTA]) AS soma, MAX([PREÇO DE LISTA]) AS maximo, MIN([PREÇO DE LISTA]) AS minimo  
FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM 
HAVING SUM([PREÇO DE LISTA]) <= 80 AND MAX([PREÇO DE LISTA]) >= 6;

