
SELECT * fROM [SUCOS_VENDAS].[dbo].[TABELA DE PRODUTOS]
WHERE [NOME DO PRODUTO] LIKE '%litros%';

SELECT * FROM [SUCOS_VENDAS].[dbo].[TABELA DE PRODUTOS]
WHERE [NOME DO PRODUTO] LIKE 'linha%';

SELECT * FROM [SUCOS_VENDAS].[dbo].[TABELA DE PRODUTOS]
WHERE [NOME DO PRODUTO] LIKE '%limão';

SELECT * FROM [SUCOS_VENDAS].[dbo].[TABELA DE PRODUTOS]
WHERE [NOME DO PRODUTO] LIKE '%manga'
AND [EMBALAGEM] = 'pet';