SELECT 
  V.MATRICULA, 
  V.[NOME], 
  COUNT(*) AS Frequência   
FROM [TABELA DE VENDEDORES] AS V INNER JOIN [NOTAS FISCAIS] AS NF ON V.MATRICULA = NF.MATRICULA
GROUP BY V.MATRICULA, V.[NOME]

SELECT 
  V.MATRICULA, 
  V.[NOME], 
  YEAR(DATA) AS Ano, 
  COUNT(*) AS Frequência 
FROM [TABELA DE VENDEDORES] AS V INNER JOIN [NOTAS FISCAIS] AS NF ON V.MATRICULA = NF.MATRICULA
GROUP BY V.MATRICULA, V.[NOME], YEAR(DATA)

SELECT 
  V.MATRICULA, 
  V.[NOME], 
  YEAR(DATA) AS Ano, 
  COUNT(*) 
FROM [TABELA DE VENDEDORES] AS V INNER JOIN [NOTAS FISCAIS] AS NF ON V.MATRICULA = NF.MATRICULA
GROUP BY V.MATRICULA, V.[NOME], YEAR(DATA)
ORDER BY YEAR(DATA), V.[NOME]

SELECT * FROM [TABELA DE VENDEDORES] AS V INNER JOIN [NOTAS FISCAIS] AS NF 
ON V.MATRICULA = NF.MATRICULA

/* old school*/
SELECT * FROM [TABELA DE VENDEDORES] AS V, [NOTAS FISCAIS] AS NF
WHERE V.MATRICULA = NF.MATRICULA


