SELECT COUNT(*) AS 'LEFT JOIN'
FROM [TABELA DE CLIENTES] LEFT JOIN [NOTAS FISCAIS] ON [TABELA DE CLIENTES].CPF = [NOTAS FISCAIS].CPF

SELECT COUNT(*) AS 'RIGHT JOIN'
FROM [TABELA DE CLIENTES] RIGHT JOIN [NOTAS FISCAIS] ON [TABELA DE CLIENTES].CPF = [NOTAS FISCAIS].CPF

SELECT 
  CL.[NOME], 
  CL.CPF,
  COUNT(*) AS 'VolumeNF'
FROM [TABELA DE CLIENTES] AS CL LEFT JOIN [NOTAS FISCAIS] AS NF ON NF.CPF = CL.CPF  
GROUP BY CL.[NOME], CL.CPF
ORDER BY 'VolumeNF'

/*Clientes que não possuem notas emitidas*/
SELECT 
  CL.[NOME], 
  CL.CPF,
  COUNT(*) AS 'VolumeNF'
FROM [TABELA DE CLIENTES] AS CL LEFT JOIN [NOTAS FISCAIS] AS NF ON NF.CPF = CL.CPF  
GROUP BY CL.[NOME], CL.CPF
HAVING count(*) = 1







