SELECT SYSDATETIME() /*Precisão*/

SELECT SYSDATETIMEOFFSET() /*Hora e diferença do funso em relação a greewich*/

SELECT SYSUTCDATETIME() /* hora de greenwich */

SELECT CURRENT_TIMESTAMP /*Pouca precisão no segundos*/

SELECT GETDATE()

SELECT GETUTCDATE()

SELECT DATENAME(YEAR,GETDATE())  /*Ano*/

SELECT DATENAME(MICROSECOND,GETDATE())

SELECT DATENAME(WEEKDAY,GETDATE()) /*Nome do dia*/

SELECT DATENAME(MINUTE,GETDATE()) /*Minuto*/

SELECT DATENAME(MONTH,GETDATE())

SELECT DATEPART(MONTH,GETDATE())

SELECT DAY(GETDATE())

SELECT YEAR(GETDATE())

SELECT DATEFROMPARTS(2015,9,1) /*Cria a data*/

SELECT DATENAME(MONTH,DATEFROMPARTS(2015,9,1)) /*Cria a data e apresenta nome por extenso*/

SELECT DATETIME2FROMPARTS(2015,9,1,13,12,11,120,4) /*Cria data com hora, minuto, segundos*/

SELECT DATEDIFF(MONTH, DATEFROMPARTS(2019,1,1), GETDATE()) /*Diferença da data informada para hoje*/

SELECT DATEADD(MONTH, 5, GETDATE()) /*Soma 5 meses na data de hoje*/

SELECT ISDATE('2018-01-01') /*Valida se é uma data*/

SELECT ISDATE('2018-25-28') /*Valida se é uma data*/

SELECT * FROM [TABELA DE CLIENTES] 
WHERE MONTH([DATA DE NASCIMENTO]) = '9';

SELECT * FROM [TABELA DE CLIENTES] 
WHERE DAY([DATA DE NASCIMENTO]) = '11';

SELECT * FROM [TABELA DE CLIENTES] 
WHERE YEAR([DATA DE NASCIMENTO]) = '1995';

SELECT [DATA], CONCAT(DATENAME(DAY, [DATA]), ' ', DATENAME(MONTH, [DATA]), ' ', DATENAME(YEAR, [DATA]))
FROM [NOTAS FISCAIS]









